name: Release
description: Runs the release process

runs:
  using: "composite"
  steps:
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release 
      shell: bash