name: Pull Request Check

on:
  pull_request:
    branches: [ develop ] 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.18.0'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm run test 