name: Docker Build and Publish

on:
  push:
    branches: [ develop ]
    paths:
      - 'CHANGELOG.md'
      - 'package.json'
      - 'package-lock.json'

jobs:
  docker:
    # todo check also all 3 files changed together 
    if: "contains(github.event.head_commit.message, 'chore(release):') && contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Debug Event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Tag name: ${{ github.ref_name }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64, linux/arm64/v8
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/recipe-vault:latest
            ${{ vars.DOCKERHUB_USERNAME }}/recipe-vault:${{ github.ref_name }} 